version: '3.8'
services:
  backend:
    container_name: Backend
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - '3001:3001'
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules/'